source 'https://github.com/CocoaPods/Specs.git'
target :YJHouse do
     platform :ios, '8.0'
     pod 'SDWebImage'
     pod 'AFNetworking'
     pod 'Masonry'
     pod 'KLCPopup'
     pod 'Mantle'
     pod 'MJRefresh'
     pod 'MBProgressHUD'
     pod 'TTRangeSlider'
     pod 'IQKeyboardManager'
     pod 'SVProgressHUD'
     pod 'AMap3DMap'
     pod 'AMapSearch'
     pod 'AMapLocation'
end
